# SPDX-FileCopyrightText: 2026 Marcel Scherello
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = [
    "tests/**", "l10n/**", "screenshots/**", "img/pictures/**", "img/**", ".**", "phpunit.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Marcel Scherello"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "js/3rdParty/chart.umd.js",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 Chart.js Contributors"
SPDX-License-Identifier = "MIT"
